name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kfunca
        uses: actions/checkout@v4
      - name: Run lint check
        run: |
          find . \( -name "*.h" -o -name "*.cpp" -o -name "*.cu" \) -exec clang-format --dry-run -Werror {} +
  cuda-env:
    runs-on: self-hosted
    steps:
      - name: Checkout kfunca
        uses: actions/checkout@v4
      - name: CUDA env test
        run: |
          set -xe
          pwd
          conda init bash
          source /home/xytpai/.bashrc
          which conda
          conda activate ci
          conda env list
          nvcc --version
          nvidia-smi
          python setup.py develop
          which python
          python -c "import kfunca; print(kfunca.__file__)"
          python -c "import kfunca; kfunca.device_info()"
