name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kfunca
        uses: actions/checkout@v4
      - name: Run lint check
        run: |
          find . \( -name "*.h" -o -name "*.cpp" -o -name "*.cu" \) -exec clang-format --dry-run -Werror {} +
  cuda-env:
    runs-on: self-hosted
    steps:
      - name: Checkout kfunca
        uses: actions/checkout@v4
      - name: CUDA env test
        run: |
          pip uninstall -y kfunca
          pip uninstall -y kfunca
          pip uninstall -y kfunca
          set -xe
          pwd
          source /home/xytpai/miniconda3/bin/activate ci
          which conda
          conda env list
          nvcc --version
          nvidia-smi
          pip install -r requirements.txt
          git submodule update --init --recursive
          python setup.py install
          for f in build/test_*.out; do ./"$f"; done
          which python
          python -c "import kfunca; print(kfunca.__file__)"
          python -c "import kfunca; kfunca.device_info()"
          python -m pytest -sv test/test_*.py
